spring.application.name=ficmart-payment-gateway

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true

# Server
server.port=${PORT:8080}
server.shutdown=graceful
server.forward-headers-strategy=framework

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.ficmart.paymentgateway=INFO
logging.level.org.hibernate.SQL=WARN

bank.base-url=${BANK_BASE_URL}